redis:
  address: localhost
  password: ""
  database: 1
  port: 6379

mongo:
  address: localhost
  password: ""
  db: 1
  port: 27017
  username: ""
  source: ""

sserver:
  firstUrl: wwww.bilibili.com
  
